id: P7D46A341
initial_creation_type: input
source_metadata:
  Title: 'Vimalakīrtinirdeśa: A Sanskrit Edition Based upon the Manuscript Newly Found
    at the Potala Palace'
  Editor: '-'
  Publisher: Taisho University Press
  Place of Publication: Tokyo
  Year: '2006'
  Vimalakīrtinirdeśa sūtram:
    Text Version: Roman
    Input Personnel: DSBC Staff
    Input Date: '2013'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:08:47.312858'
last_modified_at: '2022-03-08T16:08:47.312866'
